#
# GitHub install
#

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/4f82700
X-GitHub-Delivery: e3309f30-5325-11e8-9f2b-35faebcf4a2d
X-GitHub-Event: installation
X-Hub-Signature: sha1=d313c0c83db5e284b40a88233fb0eea6fb74150a

< ./installation_created.json

###
#
# GitHub uninstall
#

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/3783516
X-GitHub-Delivery: 19e7a2ac-5354-11e8-8972-478e4e07566a
X-GitHub-Event: installation
X-Hub-Signature: sha1=c1ac983ad63ce591b0f2df361e77fee690ea285c

< ./install_deleted.json

###
