#
# @see https://developer.github.com/v3/activity/events/types/
#

#
# "repository" "branch" "tag"
#
# @see https://developer.github.com/v3/activity/events/types/#createevent
#


### create tag

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 01e5a700-4ef2-11e8-9f1d-3cff12e0a52e
X-GitHub-Event: create
X-Hub-Signature: sha1=450921ee3a7f3aad42d498d9bb44472cd502faba

< ./create_tag.json

###
