### status pending

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 3fbd14c6-4ee5-11e8-8c55-6db697634b6c
X-GitHub-Event: status
X-Hub-Signature: sha1=d903bd3147e448d949d3e048ae0db13d82a94956

< ./status_pendng.json

### status failure

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 40d21e92-4ee5-11e8-80cc-77b1ce614bf2
X-GitHub-Event: status
X-Hub-Signature: sha1=99d089c08918f83f3a091692a1516b6e99368bb3

< ./status_failure.json
