#!/usr/bin/env sh

export DOCKER_BUILDKIT=${INPUT_DOCKER_BUILDKIT:-1}
export DOCKER_HOST=${INPUT_DOCKER_HOST}
export DOCKER_USERNAME=${INPUT_DOCKER_USERNAME}
export DOCKER_PASSWORD=${INPUT_DOCKER_PASSWORD}

# login

set +x
echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin "${INPUT_DOCKER_REGISTRY}"

# exec command

set -x

# 若 INPUT_DOCKER_REGISTRY 存在，则镜像名加上地址
[ -n "${INPUT_DOCKER_REGISTRY}" ] && INPUT_DOCKER_IMAGE="${INPUT_DOCKER_REGISTRY}/${INPUT_DOCKER_IMAGE}"

docker ${INPUT_DOCKER_COMMAND} ${INPUT_DOCKER_OPTIONS}

if [ "$INPUT_DOCKER_COMMAND" = 'build' -a "${INPUT_DOCKER_DRY_RUN}" = 0 ];then
    docker push ${INPUT_DOCKER_IMAGE}
fi
