#
# add
#

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/4f82700
X-GitHub-Delivery: fe584bb0-533d-11e8-9a2d-719d0a516c76
X-GitHub-Event: installation_repositories
X-Hub-Signature: sha1=2dcb7fdeeca3000222c47a2d2fb1c319284aafc7

< ./installation_repositories_add.json

###
#
# remove
#

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/4f82700
X-GitHub-Delivery: 7206bb1e-533e-11e8-80e6-6d01c81f3ff7
X-GitHub-Event: installation_repositories
X-Hub-Signature: sha1=60d9d60682087b4f0f97186793fd90e198adcb57

< ./installation_repositories_removed.json

###
