POST https://{{ci_host}}/webhooks/aliyun_docker_registry
Content-Type: application/json
Request URL: https://ci2.khs1994.com:10000/webhooks/aliyun_docker_registry
Request method: POST

< ./push.json

###
