### List

GET https://{{ci_host}}/api/builds
Authorization: token {{api_token}}

### error test

GET https://{{ci_host}}/api/builds?id=10&limit=2
Authorization: token {{api_token}}

### List By Repo

GET https://{{ci_host}}/api/repo/github_app/khs1994-php/khsci/builds
Authorization: token {{api_token}}

###

GET https://{{ci_host}}/api/repo/github_app/khs1994-php/khsci/builds?before=10&limit=2
Authorization: token {{api_token}}

### Find By Repo Current

GET https://{{ci_host}}/api/repo/github_app/khs1994-php/khsci/build/current

### Find

### error test not found

GET https://{{ci_host}}/api/build/12
Authorization: token {{api_token}}

###

GET https://{{ci_host}}/api/build/1
Authorization: token {{api_token}}

### Cancel

POST https://{{ci_host}}/api/build/1/cancel
Authorization: token {{api_token}}

### Restart

POST https://{{ci_host}}/api/build/1/restart
Authorization: token {{api_token}}
