GET https://{{ci_host}}/api/repo/github_app/khs1994-php/pcit/branches
Authorization: token {{api_token}}

###

GET https://{{ci_host}}/api/repo/github_app/khs1994-php/pcit/branch/master
Authorization: token {{api_token}}

###

GET https://{{ci_host}}/api/repo/github_app/khs1994-php/pcit/branch/master?before=10&limit=1
Authorization: token {{api_token}}

###
