### add

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/93ed2a1
X-GitHub-Delivery: 3c76add0-5724-11e8-8100-34ff01729cfa
X-GitHub-Event: issue_comment
X-Hub-Signature: sha1=e96850995b2b79891e083bdf5f2e57765606f1ac

< ./issue_comment_created.json

### edited

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/93ed2a1
X-GitHub-Delivery: 9375a500-5724-11e8-8f70-adfd51d95240
X-GitHub-Event: issue_comment
X-Hub-Signature: sha1=1fb9770fd5c2590204f6ec5a497191cbfb70877e

< ./issue_comment_edited.json

### deleted

POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/93ed2a1
X-GitHub-Delivery: be22bc34-5724-11e8-90de-352837d2a9ea
X-GitHub-Event: issue_comment
X-Hub-Signature: sha1=a3d93dcfba636236f6c221d50ae6456c77a40a6f

< ./issue_comment_deleted.json

###
