pipeline {
  agent any
  environment {
    DOCKER_PASSWORD = "${env.DOCKER_PASSWORD}"
    TENCENT_DOCKER_USERNAME = "${env.TENCENT_DOCKER_USERNAM}"

    DEST_DOCKER_REGISTRY = "ccr.ccs.tencentyun.com"
    REGISTRY_NAMESPACE = "pcit"
  }
  stages {
    stage("os-manifest"){
      steps {
        sh '''
        cat /etc/os-release
        '''
      }
    }

    stage('同步镜像') {
      steps {
        sh "curl -L -O https://gitee.com/pcit-ce/pcit/raw/master/.docker/docker-image-sync.json"

        sh "docker run -i --rm -e DEST_DOCKER_USERNAME=\${TENCENT_DOCKER_USERNAME} \
            -e DEST_DOCKER_PASSWORD=\${DOCKER_PASSWORD} \
            -e SOURCE_DOCKER_REGISTRY=mirror.ccs.tencentyun.com \
            -e DEST_DOCKER_REGISTRY=\${DEST_DOCKER_REGISTRY} \
            -e SOURCE_NAMESPACE=\${REGISTRY_NAMESPACE} \
            -e DEST_NAMESPACE=\${REGISTRY_NAMESPACE} \
            -e CI=true \
            -v \$PWD/docker-image-sync.json:/root/lnmp/windows/docker-image-sync.json \
            khs1994/docker-image-sync"
      }
    }

  }
}
