POST https://{{ci_host}}/webhooks/github_app
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/93ed2a1
X-GitHub-Delivery: 1c51d120-55ac-11e8-95ac-ebd3c70d8d94
X-GitHub-Event: issues
X-Hub-Signature: sha1=849e99465295a68f57ad552370c3634c21b3b8e4

< ./issue_opened.json

###
