### pull_request opened

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: d789f8a0-4f58-11e8-948c-7bb71b552219
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=c28b3eaf3794d1eab602631e1ef103e5900fb2fd

< ./pull_request_opened.json

### pull_request synchronize

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 36b62330-4f59-11e8-83b1-8ad2ca72e506
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=4c47850fe70450a7fbd1e6bbf32b44d53e15b23c

< ./pull_request_synchronize.json

### pull_request closed

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 8a15ac80-4f59-11e8-82b9-4aa1a12f39a9
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=20977f29a5aaa366886715f1ad7247d9d66c02c2

< ./pull_request_closed.json

###
