POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/4f82700
X-GitHub-Delivery: 7e736e74-5267-11e8-8ee3-fa72517681a3
X-GitHub-Event: push
X-Hub-Signature: sha1=e76e60d903c010e45ca28c7c42ae50d3d1b513dc

{
  "ref": "refs/heads/dev",
  "before": "f879b7dc14c0dbb12152ae45e84fb598d61fe46d",
  "after": "0d943ab99892126024822e4031cb903c0d46837f",
  "created": false,
  "deleted": false,
  "forced": true,
  "base_ref": null,
  "compare": "https://github.com/khs1994-php/khsci/compare/f879b7dc14c0...0d943ab99892",
  "commits": [
    {
      "id": "0d943ab99892126024822e4031cb903c0d46837f",
      "tree_id": "edb5eaa8d85eb2232aa824844d8e4abf3b6e8332",
      "distinct": true,
      "message": "Update",
      "timestamp": "2018-05-07T23:53:15+08:00",
      "url": "https://github.com/khs1994-php/khsci/commit/0d943ab99892126024822e4031cb903c0d46837f",
      "author": {
        "name": "khs1994",
        "email": "khs1994@khs1994.com",
        "username": "khs1994"
      },
      "committer": {
        "name": "khs1994",
        "email": "khs1994@khs1994.com",
        "username": "khs1994"
      },
      "added": [

      ],
      "removed": [
        "src/KhsCI/Service/Queue/UpdateRepoCollaborators.php"
      ],
      "modified": [
        "public/app/Console/Queue.php",
        "src/KhsCI/KhsCI.php",
        "src/KhsCI/Providers/QueueProvider.php"
      ]
    }
  ],
  "head_commit": {
    "id": "0d943ab99892126024822e4031cb903c0d46837f",
    "tree_id": "edb5eaa8d85eb2232aa824844d8e4abf3b6e8332",
    "distinct": true,
    "message": "Update",
    "timestamp": "2018-05-07T23:53:15+08:00",
    "url": "https://github.com/khs1994-php/khsci/commit/0d943ab99892126024822e4031cb903c0d46837f",
    "author": {
      "name": "khs1994",
      "email": "khs1994@khs1994.com",
      "username": "khs1994"
    },
    "committer": {
      "name": "khs1994",
      "email": "khs1994@khs1994.com",
      "username": "khs1994"
    },
    "added": [

    ],
    "removed": [
      "src/KhsCI/Service/Queue/UpdateRepoCollaborators.php"
    ],
    "modified": [
      "public/app/Console/Queue.php",
      "src/KhsCI/KhsCI.php",
      "src/KhsCI/Providers/QueueProvider.php"
    ]
  },
  "repository": {
    "id": 1000000001,
    "name": "test",
    "full_name": "khs1994-php/test",
    "owner": {
      "name": "khs1994-php",
      "email": "khs1994@khs1994.com",
      "login": "khs1994-php",
      "id": 31461768,
      "avatar_url": "https://avatars0.githubusercontent.com/u/31461768?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/khs1994-php",
      "html_url": "https://github.com/khs1994-php",
      "followers_url": "https://api.github.com/users/khs1994-php/followers",
      "following_url": "https://api.github.com/users/khs1994-php/following{/other_user}",
      "gists_url": "https://api.github.com/users/khs1994-php/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/khs1994-php/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/khs1994-php/subscriptions",
      "organizations_url": "https://api.github.com/users/khs1994-php/orgs",
      "repos_url": "https://api.github.com/users/khs1994-php/repos",
      "events_url": "https://api.github.com/users/khs1994-php/events{/privacy}",
      "received_events_url": "https://api.github.com/users/khs1994-php/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/khs1994-php/khsci",
    "description": "[TODO] 仿照 Drone CI Travis CI 使用 PHP 实现完全基于 Docker 的 CI 系统",
    "fork": false,
    "url": "https://github.com/khs1994-php/khsci",
    "forks_url": "https://api.github.com/repos/khs1994-php/khsci/forks",
    "keys_url": "https://api.github.com/repos/khs1994-php/khsci/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/khs1994-php/khsci/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/khs1994-php/khsci/teams",
    "hooks_url": "https://api.github.com/repos/khs1994-php/khsci/hooks",
    "issue_events_url": "https://api.github.com/repos/khs1994-php/khsci/issues/events{/number}",
    "events_url": "https://api.github.com/repos/khs1994-php/khsci/events",
    "assignees_url": "https://api.github.com/repos/khs1994-php/khsci/assignees{/user}",
    "branches_url": "https://api.github.com/repos/khs1994-php/khsci/branches{/branch}",
    "tags_url": "https://api.github.com/repos/khs1994-php/khsci/tags",
    "blobs_url": "https://api.github.com/repos/khs1994-php/khsci/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/khs1994-php/khsci/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/khs1994-php/khsci/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/khs1994-php/khsci/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/khs1994-php/khsci/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/khs1994-php/khsci/languages",
    "stargazers_url": "https://api.github.com/repos/khs1994-php/khsci/stargazers",
    "contributors_url": "https://api.github.com/repos/khs1994-php/khsci/contributors",
    "subscribers_url": "https://api.github.com/repos/khs1994-php/khsci/subscribers",
    "subscription_url": "https://api.github.com/repos/khs1994-php/khsci/subscription",
    "commits_url": "https://api.github.com/repos/khs1994-php/khsci/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/khs1994-php/khsci/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/khs1994-php/khsci/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/khs1994-php/khsci/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/khs1994-php/khsci/contents/{+path}",
    "compare_url": "https://api.github.com/repos/khs1994-php/khsci/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/khs1994-php/khsci/merges",
    "archive_url": "https://api.github.com/repos/khs1994-php/khsci/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/khs1994-php/khsci/downloads",
    "issues_url": "https://api.github.com/repos/khs1994-php/khsci/issues{/number}",
    "pulls_url": "https://api.github.com/repos/khs1994-php/khsci/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/khs1994-php/khsci/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/khs1994-php/khsci/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/khs1994-php/khsci/labels{/name}",
    "releases_url": "https://api.github.com/repos/khs1994-php/khsci/releases{/id}",
    "deployments_url": "https://api.github.com/repos/khs1994-php/khsci/deployments",
    "created_at": 1517105388,
    "updated_at": "2018-05-07T15:24:29Z",
    "pushed_at": 1525746508,
    "git_url": "git://github.com/khs1994-php/khsci.git",
    "ssh_url": "git@github.com:khs1994-php/khsci.git",
    "clone_url": "https://github.com/khs1994-php/khsci.git",
    "svn_url": "https://github.com/khs1994-php/khsci",
    "homepage": "https://ci.khs1994.com/api",
    "size": 216,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "PHP",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 10,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 0,
    "open_issues": 10,
    "watchers": 1,
    "default_branch": "master",
    "stargazers": 1,
    "master_branch": "master",
    "organization": "khs1994-php"
  },
  "pusher": {
    "name": "khs1994",
    "email": "khs1994@khs1994.com"
  },
  "organization": {
    "login": "khs1994-php",
    "id": 31461768,
    "url": "https://api.github.com/orgs/khs1994-php",
    "repos_url": "https://api.github.com/orgs/khs1994-php/repos",
    "events_url": "https://api.github.com/orgs/khs1994-php/events",
    "hooks_url": "https://api.github.com/orgs/khs1994-php/hooks",
    "issues_url": "https://api.github.com/orgs/khs1994-php/issues",
    "members_url": "https://api.github.com/orgs/khs1994-php/members{/member}",
    "public_members_url": "https://api.github.com/orgs/khs1994-php/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/31461768?v=4",
    "description": "developer.khs1994.com PHP 项目 Powered By khs1994-docker/lnmp"
  },
  "sender": {
    "login": "khs1994",
    "id": 16733187,
    "avatar_url": "https://avatars2.githubusercontent.com/u/16733187?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/khs1994",
    "html_url": "https://github.com/khs1994",
    "followers_url": "https://api.github.com/users/khs1994/followers",
    "following_url": "https://api.github.com/users/khs1994/following{/other_user}",
    "gists_url": "https://api.github.com/users/khs1994/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/khs1994/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/khs1994/subscriptions",
    "organizations_url": "https://api.github.com/users/khs1994/orgs",
    "repos_url": "https://api.github.com/users/khs1994/repos",
    "events_url": "https://api.github.com/users/khs1994/events{/privacy}",
    "received_events_url": "https://api.github.com/users/khs1994/received_events",
    "type": "User",
    "site_admin": false
  }
}

### commit message include [skip ci]

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/4f82700
X-GitHub-Delivery: 7e736e74-5267-11e8-8ee3-fa72517681a3
X-GitHub-Event: push
X-Hub-Signature: sha1=e76e60d903c010e45ca28c7c42ae50d3d1b513dc

{
  "ref": "refs/heads/dev",
  "before": "f879b7dc14c0dbb12152ae45e84fb598d61fe46d",
  "after": "0d943ab99892126024822e4031cb903c0d46837f",
  "created": false,
  "deleted": false,
  "forced": true,
  "base_ref": null,
  "compare": "https://github.com/khs1994-php/khsci/compare/f879b7dc14c0...0d943ab99892",
  "commits": [
    {
      "id": "0d943ab99892126024822e4031cb903c0d46837f",
      "tree_id": "edb5eaa8d85eb2232aa824844d8e4abf3b6e8332",
      "distinct": true,
      "message": "Update [skip ci]",
      "timestamp": "2018-05-07T23:53:15+08:00",
      "url": "https://github.com/khs1994-php/khsci/commit/0d943ab99892126024822e4031cb903c0d46837f",
      "author": {
        "name": "khs1994",
        "email": "khs1994@khs1994.com",
        "username": "khs1994"
      },
      "committer": {
        "name": "khs1994",
        "email": "khs1994@khs1994.com",
        "username": "khs1994"
      },
      "added": [

      ],
      "removed": [
        "src/KhsCI/Service/Queue/UpdateRepoCollaborators.php"
      ],
      "modified": [
        "public/app/Console/Queue.php",
        "src/KhsCI/KhsCI.php",
        "src/KhsCI/Providers/QueueProvider.php"
      ]
    }
  ],
  "head_commit": {
    "id": "0d943ab99892126024822e4031cb903c0d46837f",
    "tree_id": "edb5eaa8d85eb2232aa824844d8e4abf3b6e8332",
    "distinct": true,
    "message": "Update [skip ci]",
    "timestamp": "2018-05-07T23:53:15+08:00",
    "url": "https://github.com/khs1994-php/khsci/commit/0d943ab99892126024822e4031cb903c0d46837f",
    "author": {
      "name": "khs1994",
      "email": "khs1994@khs1994.com",
      "username": "khs1994"
    },
    "committer": {
      "name": "khs1994",
      "email": "khs1994@khs1994.com",
      "username": "khs1994"
    },
    "added": [

    ],
    "removed": [
      "src/KhsCI/Service/Queue/UpdateRepoCollaborators.php"
    ],
    "modified": [
      "public/app/Console/Queue.php",
      "src/KhsCI/KhsCI.php",
      "src/KhsCI/Providers/QueueProvider.php"
    ]
  },
  "repository": {
    "id": 100000001,
    "name": "test",
    "full_name": "khs1994-php/test",
    "owner": {
      "name": "khs1994-php",
      "email": "khs1994@khs1994.com",
      "login": "khs1994-php",
      "id": 31461768,
      "avatar_url": "https://avatars0.githubusercontent.com/u/31461768?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/khs1994-php",
      "html_url": "https://github.com/khs1994-php",
      "followers_url": "https://api.github.com/users/khs1994-php/followers",
      "following_url": "https://api.github.com/users/khs1994-php/following{/other_user}",
      "gists_url": "https://api.github.com/users/khs1994-php/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/khs1994-php/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/khs1994-php/subscriptions",
      "organizations_url": "https://api.github.com/users/khs1994-php/orgs",
      "repos_url": "https://api.github.com/users/khs1994-php/repos",
      "events_url": "https://api.github.com/users/khs1994-php/events{/privacy}",
      "received_events_url": "https://api.github.com/users/khs1994-php/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/khs1994-php/khsci",
    "description": "[TODO] 仿照 Drone CI Travis CI 使用 PHP 实现完全基于 Docker 的 CI 系统",
    "fork": false,
    "url": "https://github.com/khs1994-php/khsci",
    "forks_url": "https://api.github.com/repos/khs1994-php/khsci/forks",
    "keys_url": "https://api.github.com/repos/khs1994-php/khsci/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/khs1994-php/khsci/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/khs1994-php/khsci/teams",
    "hooks_url": "https://api.github.com/repos/khs1994-php/khsci/hooks",
    "issue_events_url": "https://api.github.com/repos/khs1994-php/khsci/issues/events{/number}",
    "events_url": "https://api.github.com/repos/khs1994-php/khsci/events",
    "assignees_url": "https://api.github.com/repos/khs1994-php/khsci/assignees{/user}",
    "branches_url": "https://api.github.com/repos/khs1994-php/khsci/branches{/branch}",
    "tags_url": "https://api.github.com/repos/khs1994-php/khsci/tags",
    "blobs_url": "https://api.github.com/repos/khs1994-php/khsci/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/khs1994-php/khsci/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/khs1994-php/khsci/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/khs1994-php/khsci/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/khs1994-php/khsci/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/khs1994-php/khsci/languages",
    "stargazers_url": "https://api.github.com/repos/khs1994-php/khsci/stargazers",
    "contributors_url": "https://api.github.com/repos/khs1994-php/khsci/contributors",
    "subscribers_url": "https://api.github.com/repos/khs1994-php/khsci/subscribers",
    "subscription_url": "https://api.github.com/repos/khs1994-php/khsci/subscription",
    "commits_url": "https://api.github.com/repos/khs1994-php/khsci/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/khs1994-php/khsci/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/khs1994-php/khsci/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/khs1994-php/khsci/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/khs1994-php/khsci/contents/{+path}",
    "compare_url": "https://api.github.com/repos/khs1994-php/khsci/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/khs1994-php/khsci/merges",
    "archive_url": "https://api.github.com/repos/khs1994-php/khsci/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/khs1994-php/khsci/downloads",
    "issues_url": "https://api.github.com/repos/khs1994-php/khsci/issues{/number}",
    "pulls_url": "https://api.github.com/repos/khs1994-php/khsci/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/khs1994-php/khsci/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/khs1994-php/khsci/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/khs1994-php/khsci/labels{/name}",
    "releases_url": "https://api.github.com/repos/khs1994-php/khsci/releases{/id}",
    "deployments_url": "https://api.github.com/repos/khs1994-php/khsci/deployments",
    "created_at": 1517105388,
    "updated_at": "2018-05-07T15:24:29Z",
    "pushed_at": 1525746508,
    "git_url": "git://github.com/khs1994-php/khsci.git",
    "ssh_url": "git@github.com:khs1994-php/khsci.git",
    "clone_url": "https://github.com/khs1994-php/khsci.git",
    "svn_url": "https://github.com/khs1994-php/khsci",
    "homepage": "https://ci.khs1994.com/api",
    "size": 216,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "PHP",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 10,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 0,
    "open_issues": 10,
    "watchers": 1,
    "default_branch": "master",
    "stargazers": 1,
    "master_branch": "master",
    "organization": "khs1994-php"
  },
  "pusher": {
    "name": "khs1994",
    "email": "khs1994@khs1994.com"
  },
  "organization": {
    "login": "khs1994-php",
    "id": 31461768,
    "url": "https://api.github.com/orgs/khs1994-php",
    "repos_url": "https://api.github.com/orgs/khs1994-php/repos",
    "events_url": "https://api.github.com/orgs/khs1994-php/events",
    "hooks_url": "https://api.github.com/orgs/khs1994-php/hooks",
    "issues_url": "https://api.github.com/orgs/khs1994-php/issues",
    "members_url": "https://api.github.com/orgs/khs1994-php/members{/member}",
    "public_members_url": "https://api.github.com/orgs/khs1994-php/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/31461768?v=4",
    "description": "developer.khs1994.com PHP 项目 Powered By khs1994-docker/lnmp"
  },
  "sender": {
    "login": "khs1994",
    "id": 16733187,
    "avatar_url": "https://avatars2.githubusercontent.com/u/16733187?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/khs1994",
    "html_url": "https://github.com/khs1994",
    "followers_url": "https://api.github.com/users/khs1994/followers",
    "following_url": "https://api.github.com/users/khs1994/following{/other_user}",
    "gists_url": "https://api.github.com/users/khs1994/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/khs1994/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/khs1994/subscriptions",
    "organizations_url": "https://api.github.com/users/khs1994/orgs",
    "repos_url": "https://api.github.com/users/khs1994/repos",
    "events_url": "https://api.github.com/users/khs1994/events{/privacy}",
    "received_events_url": "https://api.github.com/users/khs1994/received_events",
    "type": "User",
    "site_admin": false
  }
}

###
