### release

POST https://{{ci_host}}/webhooks/github
Request URL: https://ci2.khs1994.com:10000/webhooks/github
Request method: POST
content-type: application/json
Expect:
User-Agent: GitHub-Hookshot/5335d90
X-GitHub-Delivery: 01c21970-4ef2-11e8-8a56-6fee204f8f92
X-GitHub-Event: release
X-Hub-Signature: sha1=73d1bc63956c0e71687e9300eb145ec185f2d635

< ./release.json
